### ISSUE TITLE
Use the actual generation groups instead of trying to deduce them ourselves

### ISSUE THREAD

**Issue by leoetlino** [zeldamods/radar-totk#1]

**Comment by savage13** [comment]
Would this be `SimultaneousGroups`?

**Comment by leoetlino** [comment]
Yep. I'll fix this now

**Comment by savage13** [comment]
I wonder if the Links with `Dst`/`Src` and those in the `AiGroups` section are consistent with those in `SimultaneousGroups`?

**Comment by leoetlino** [comment]
Not necessarily, and in fact I noticed this because the gen group we were deducing using the entity links was a strict subset of the actual simultaneous generation group and missing several entities.
